roles:

collections:

  # local collections for testing
  - source: ../tosmi
    type: subdirs

  # general collections
  - name: kubernetes.core
    version: 5.0.0
    source: https://console.redhat.com/api/automation-hub/

  - name: redhat.openshift_virtualization
    version: 2.0.0
    source: https://console.redhat.com/api/automation-hub/

  - name: redhat.insights
    version: 1.3.0
    source: https://console.redhat.com/api/automation-hub/

  - name: ansible.posix
    version: 1.5.4
    source: https://galaxy.ansible.com

  - name: community.libvirt
    version: 1.3.0
    source: https://galaxy.ansible.com

  - name: community.docker
    version: 3.11.0
    source: https://galaxy.ansible.com

  - name: community.general
    version: 9.2.0
    source: https://galaxy.ansible.com

  - name: ansible.controller
    version: 4.5.8
    source: https://console.redhat.com/api/automation-hub/

  - name:  amazon.aws
    version: 8.2.1
    source: https://console.redhat.com/api/automation-hub/

  - name:  redhat.satellite
    version: 4.1.0
    source: https://console.redhat.com/api/automation-hub/
