roles:
  - name: geerlingguy.gitlab
    version: 3.1.0

collections:
  - name: ansible.posix
    version: 1.2.0

  - name: ansible.tower
    version: 3.8.3
    source: https://console.redhat.com/api/automation-hub/

  - name:  amazon.aws
    version: 1.5.0
    source: https://console.redhat.com/api/automation-hub/
