roles:

collections:

  # local collections for testing
  - source: ../tosmi
    type: subdirs

  # general collections
  - name: kubernetes.core
    version: 6.5.0
    source: https://galaxy.ansible.com

  - name: community.libvirt
    version: 2.3.0
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: 1.20.2
    source: https://galaxy.ansible.com

  - name: community.general
    version: 13.3.0
    source: https://galaxy.ansible.com
