---
# tasks file for loadbalancer
- name: Install required packages
  yum:
    state: present
    name:
      - bind-utils
      - firewalld
      - haproxy
      - libreswan

- name: Add tower service ip address with nmcli
  command: /bin/nmcli con modify 'System eth0' +ipv4.addresses "10.0.0.212/24"
  notify:
    - Restart NetworkManager

- name: Add automation controller service ip address with nmcli
  command: /bin/nmcli con modify 'System eth0' +ipv4.addresses "10.0.0.225/24"
  notify:
    - Restart NetworkManager

- name: Allow incoming HTTP connections
  ansible.posix.firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled

- name: Allow incoming HTTPS connections
  ansible.posix.firewalld:
    service: https
    permanent: yes
    immediate: yes
    state: enabled


- name: Allow incoming HTTPS connections
  ansible.posix.firewalld:
    service: https
    permanent: yes
    immediate: yes
    state: enabled

- name: Allow incoming PostgreSQL connections
  ansible.posix.firewalld:
    port: 5432/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: Allow incoming HAproxy stats connections
  ansible.posix.firewalld:
    port: 9000/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: Allow incoming OpenShift API connections
  ansible.posix.firewalld:
    port: 6443/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: Allow incoming OpenShift machine config server connections
  ansible.posix.firewalld:
    port: 22623/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: Set SELinux haproxy_connect_any flag on and keep it persistent across reboots
  ansible.posix.seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes

- name: Deploy HAProxy config template
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart HAProxy
