---
- name: "Add lifecycle environments"
  redhat.satellite.lifecycle_environment:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "Lab"
    label: "lab"
    prior: "Library"
    description: "The Lab environment"
    state: "present"

- name: Create content views for RHEL 9 kickstart
  redhat.satellite.content_view:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CV: RHEL 9 kickstart"
    repositories:
      - name: 'Red Hat Enterprise Linux 9 for x86_64 - AppStream Kickstart 9.0'
        product: 'Red Hat Enterprise Linux for x86_64'
      - name: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.0'
        product: 'Red Hat Enterprise Linux for x86_64'
  register: cv_rhel9kickstart

- name: Create content views for RHEL 9 (baseos + appstream)
  redhat.satellite.content_view:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CV: RHEL 9"
    repositories:
      - name: 'Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9'
        product: 'Red Hat Enterprise Linux for x86_64'
      - name: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9'
        product: 'Red Hat Enterprise Linux for x86_64'
  register: cv_rhel9

- name: Create content views for RHEL 9 fast datapath
  redhat.satellite.content_view:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CV: RHEL 9 Fast Datapath"
    repositories:
      - name: 'Fast Datapath for RHEL 9 x86_64 RPMs'
        product: 'Red Hat Enterprise Linux Fast Datapath'
  register: cv_rhel9_datapath

- name: Create content views for RHEL 9 Ansible
  redhat.satellite.content_view:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CV: RHEL 9 Ansible"
    repositories:
      - name: 'Red Hat Ansible Engine 2 for RHEL 8 x86_64 RPMs'
        product: 'Red Hat Ansible Engine'
      - name: 'Red Hat Ansible Automation Platform 2.2 for RHEL 9 x86_64 RPMs'
        product: 'Red Hat Ansible Automation Platform'
  register: cv_rhel9_ansible

- name: "Create a composite content view for RHEL 9"
  redhat.satellite.content_view:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CCV: RHEL 9"
    composite: true
    auto_publish: false
    components:
      - content_view: "CV: RHEL 9"
        latest: true
      - content_view: "CV: RHEL 9 Fast Datapath"
        latest: true
      - content_view: "CV: RHEL 9 Ansible"
        latest: true
  register: ccv_rhel9
...
