---
- name: "Add lifecycle environments"
  theforeman.foreman.lifecycle_environment:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "Lab"
    label: "lab"
    prior: "Library"
    description: "The Lab environment"
    state: "present"

- name: Create content views for RHEL 8 kickstart
  theforeman.foreman.content_view:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CV: RHEL 8 kickstart"
    repositories:
      - name: 'Red Hat Enterprise Linux 8 for x86_64 - AppStream Kickstart 8.5'
        product: 'Red Hat Enterprise Linux for x86_64'
      - name: 'Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.5'
        product: 'Red Hat Enterprise Linux for x86_64'
  register: cv_rhel8kickstart

- name: Create content views for RHEL 8 (baseos + appstream)
  theforeman.foreman.content_view:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CV: RHEL 8"
    repositories:
      - name: 'Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8'
        product: 'Red Hat Enterprise Linux for x86_64'
      - name: 'Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8'
        product: 'Red Hat Enterprise Linux for x86_64'
  register: cv_rhel8

- name: Create content view for RHEL 8 satellite tools
  theforeman.foreman.content_view:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CV: RHEL 8 Satellite Tools"
    repositories:
      - name: "Red Hat Satellite Tools {{ satellite_tools_version }} for RHEL 8 x86_64 RPMs"
        product: 'Red Hat Enterprise Linux for x86_64'
  register: cv_rhel8_sattools

- name: Create content views for RHEL 8 fast datapath
  theforeman.foreman.content_view:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CV: RHEL 8 Fast Datapath"
    repositories:
      - name: 'Fast Datapath for RHEL 8 x86_64 RPMs'
        product: 'Red Hat Enterprise Linux Fast Datapath'
  register: cv_rhel8_datapath

- name: Create content views for RHEL 8 Ansible
  theforeman.foreman.content_view:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CV: RHEL 8 Ansible"
    repositories:
      - name: 'Red Hat Ansible Engine 2 for RHEL 8 x86_64 RPMs'
        product: 'Red Hat Ansible Engine'
  register: cv_rhel8_ansible

- name: "Create a composite content view for RHEL 8 RHEV"
  theforeman.foreman.content_view:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CCV: RHEL 8 RHEV"
    composite: true
    auto_publish: false
    components:
      - content_view: "CV: RHEL 8"
        latest: true
      - content_view: "CV: RHEL 8 Satellite Tools"
        latest: true
      - content_view: "CV: RHEL 8 Ansible"
        latest: true
  register: ccv_rhev

- name: "Create a composite content view for RHEL 8"
  theforeman.foreman.content_view:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    name: "CCV: RHEL 8"
    composite: true
    auto_publish: false
    components:
      - content_view: "CV: RHEL 8"
        latest: true
      - content_view: "CV: RHEL 8 Satellite Tools"
        latest: true
      - content_view: "CV: RHEL 8 Fast Datapath"
        latest: true
      - content_view: "CV: RHEL 8 Ansible"
        latest: true
  register: ccv_rhel8

...
