# used for debugging
#
# - name: "Search for possible repository sets of a product"
#   redhat.satellite.resource_info:
#     username: "{{ satellite_admin_username }}"
#     password: "{{ satellite_admin_password }}"
#     server_url: "{{ satellite_url}}"
#     validate_certs: false
#     organization: "{{ satellite_organization }}"
#     resource: repository_sets
#     search: product_name="Red Hat Enterprise Linux Server"
#   register: data
# - name: "Output found repository sets, see the contentUrl section for possible repository substitutions"
#   debug:
#     var: data

- name: Enable RHEL 9 OS repos
  redhat.satellite.repository_set:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    label: "{{ item }}"
    repositories:
      - releasever: "9"
    state: enabled
  loop:
    - rhel-9-for-x86_64-appstream-rpms
    - rhel-9-for-x86_64-baseos-rpms
  register: rhel9_repos

- name: Enable kickstart RHEL 9 OS repos
  redhat.satellite.repository_set:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    label: "{{ item }}"
    repositories:
      - releasever: "9.0"
    state: enabled
  loop:
    - rhel-9-for-x86_64-baseos-kickstart
    - rhel-9-for-x86_64-appstream-kickstart
  register: rhel9_kickstart

- name: Enable additional RHEL 9 repos
  redhat.satellite.repository_set:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    organization: "{{ satellite_organization }}"
    label: "{{ item }}"
    all_repositories: yes
    state: enabled
  loop:
    - fast-datapath-for-rhel-9-x86_64-rpms
    - ansible-automation-platform-2.2-for-rhel-9-x86_64-rpms
  register: rhel9_additional

- name: "Sync RHEL 9 repositories"
  redhat.satellite.repository_sync:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url}}"
    validate_certs: false
    product: "{{ item }}"
    organization: "Lab"
  loop:
    - "Red Hat Enterprise Linux Fast Datapath"
    - "Red Hat Enterprise Linux for x86_64"
    - "Red Hat Ansible Automation Platform 2.2 for RHEL 9 x86_64 RPMs"
  when: (rhel9_repos.changed or rhel9_kickstart.changed or rhel9_additional.changed or)
