---
- name: Install node exporter
  unarchive:
    src: "{{ monitoring_node_exporter_base_url }}/v{{ monitoring_node_exporter_version}}/node_exporter-{{ monitoring_node_exporter_version}}.linux-{{ monitoring_node_exporter_platform }}.tar.gz"
    dest: /usr/local/bin
