---
- name: Download node_exporter
  get_url:
    url: "{{ monitoring_node_exporter_base_url }}/v{{ monitoring_node_exporter_version}}/node_exporter-{{ monitoring_node_exporter_version}}.linux-{{ monitoring_node_exporter_platform }}.tar.gz"
    dest: /tmp/

- name: Extract node export to {{ monitoring_node_exporter_dest }}
  unarchive:
    src: "/tmp/node_exporter-{{ monitoring_node_exporter_version}}.linux-{{ monitoring_node_exporter_platform }}.tar.gz"
    dest: "{{ monitoring_node_exporter_dest }}"
    remote_src: yes
