- name: Create the cluster base directory
  file:
    state: directory
    path: "{{ aws_cluster_base_directory }}"

- name: Create the cluster directory
  file:
    state: directory
    path: "{{ aws_cluster_base_directory }}/{{ aws_cluster_name }}-{{ aws_ocp_cluster_version }}"

- name: Check if the installer is already there
  stat:
    path: "{{ aws_cluster_base_directory }}/{{ aws_cluster_name }}-{{ aws_ocp_cluster_version }}/openshift-install"
  register: aws_ocp_installer

- name: Download and extract the installer
  ansible.builtin.unarchive:
    src: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ aws_ocp_cluster_version }}/openshift-install-linux.tar.gz""
    dest: "{{ aws_cluster_base_directory }}/{{ aws_cluster_name }}-{{ aws_ocp_cluster_vesion }}"
    remote_src: yes
  when:
    - aws_skip_installer_download is not defined
    - not aws_ocp_installer.stat.exists

- name: Template install-config.yaml
  ansible.builtin.template:
    src: install-config.yaml.j2
    dest: "{{ aws_cluster_base_directory }}/{{ aws_cluster_name }}-{{ aws_ocp_cluster_version }}/install-config.yaml"

- name: Creating cluster {{ aws_cluster_name }}
  command: ./openshift-install create cluster --dir=.
  args:
    chdir: "{{ aws_cluster_base_directory }}/{{ aws_cluster_name }}-{{aws_ocp_cluster_version }}"
