---
# - name: Create Ansible Tower hosts on box02
#   gather_facts: no
#   become: yes
#   hosts:
#     - box01.lan.stderr.at
#   vars:
#     rhn:
#       host: https://satellite.lan.stderr.at
#       org_id: "1"
#     lab:
#       ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIYhjnWzsArZVyyTa1E6sDbH06rUGDAhAF3bf3pmeBtm toni@stderr.at"
#       name: infra
#       network:
#         type: bridge
#         name: bridge0
#       hosts:
#         - name: automationcontroller01
#           network: bridge0
#           macaddr: "52:54:00:01:52:26"
#           ipaddr: "10.0.0.226"
#           # disksize: 20
#           memory: 5210
#           cpu: 2
#           register: yes
#           activationkey: RHEL8
#           image: rhel-8.5-x86_64-kvm.qcow2
#   roles:
#     - lab

# - name: Create Ansible Tower hosts on box03
#   gather_facts: no
#   become: yes
#   hosts:
#     - box02.lan.stderr.at
#   vars:
#     rhn:
#       host: https://satellite.lan.stderr.at
#       org_id: "1"
#     lab:
#       ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIYhjnWzsArZVyyTa1E6sDbH06rUGDAhAF3bf3pmeBtm toni@stderr.at"
#       name: infra
#       network:
#         type: bridge
#         name: bridge0
#       hosts:
#         - name: automationcontroller02
#           network: bridge0
#           macaddr: "52:54:00:01:52:27"
#           ipaddr: "10.0.0.227"
#           # disksize: 20G
#           memory: 5120
#           cpu: 2
#           register: yes
#           activationkey: RHEL8
#           image: rhel-8.5-x86_64-kvm.qcow2
#         - name: automationhub
#           network: bridge0
#           macaddr: "52:54:00:01:52:29"
#           ipaddr: "10.0.0.229"
#           # disksize: 20G
#           memory: 5120
#           cpu: 2
#           register: yes
#           activationkey: RHEL8
#           image: rhel-8.5-x86_64-kvm.qcow2
#   roles:
#      - lab

# - name: Create Ansible Tower hosts on box03
#   gather_facts: no
#   become: yes
#   hosts:
#     - box03.lan.stderr.at
#   vars:
#     rhn:
#       host: https://satellite.lan.stderr.at
#       org_id: "1"
#     lab:
#       ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIYhjnWzsArZVyyTa1E6sDbH06rUGDAhAF3bf3pmeBtm toni@stderr.at"
#       name: infra
#       network:
#         type: bridge
#         name: bridge0
#       hosts:
#         - name: automationcontroller03
#           network: bridge0
#           macaddr: "52:54:00:01:52:28"
#           ipaddr: "10.0.0.228"
#           # disksize: 20G
#           memory: 5120
#           cpu: 2
#           register: yes
#           activationkey: RHEL8
#           image: rhel-8.5-x86_64-kvm.qcow2
#   roles:
#      - lab

- name: Configure Ansible Tower
  gather_facts: no
  hosts:
    - automationplatform
  roles:
    - controller
