- name: Create monitor host
  gather_facts: no
  become: yes
  hosts:
    - box01.lan.stderr.at
  vars:
    rhn:
      host: https://satellite.lan.stderr.at
      org_id: 1
    lab:
      ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIYhjnWzsArZVyyTa1E6sDbH06rUGDAhAF3bf3pmeBtm toni@stderr.at"
      name: monitor
      network:
        type: bridge
        name: bridge0
      hosts:
        - name: monitor
          network: bridge0
          macaddr: "52:54:00:01:52:18"
          ipaddr: "10.0.0.218"
          memory: 8192
          cpu: 2
          register: yes
          activationkey: "RHEL 8"
          image: rhel-8.4-x86_64-kvm.qcow2
          disksize: 150G
  roles:
    - lab

- name: Configure monitor host
  hosts: monitor.lan.stderr.at
  gather_facts: yes
  roles:
    - monitoring
    - monitor
