---
- name: Create Satellite hosts on box02
  gather_facts: no
  become: yes
  hosts:
    - box02.lan.stderr.at
  vars:
    # rhn:
    #   host: https://satellite.lan.stderr.at
    #   org_id: "1"
    lab:
      ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIYhjnWzsArZVyyTa1E6sDbH06rUGDAhAF3bf3pmeBtm toni@stderr.at"
      name: infra
      network:
        type: bridge
        name: bridge0
      hosts:
        - name: sat
          network: bridge0
          macaddr: "52:54:00:01:52:13"
          ipaddr: "10.0.0.212"
          disksize: 200G
          memory: 16384
          cpu: 2
          register: yes
          activationkey: RHEL 8
          image: rhel-8.6-x86_64-kvm.qcow2

  roles:
    - lab

- name: Configure Lab Red Hat Satellite
  hosts:
    - sat.lan.stderr.at
  roles:
    # - monitoring
    - satellite
