# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

  # external_labels:
  #   monitor: codelab
  #   foo: bar

rule_files:
  - "rules/*.rules"

# alerting:
#   alertmanagers:
#     - scheme: https
#       static_configs:
#         - targets:
#             - "1.2.3.4:9093"
#             - "1.2.3.5:9093"
#             - "1.2.3.6:9093"

scrape_configs:
  - job_name: diskstation
    static_configs:
      - targets:
        - ds01.lan.stderr.at  # SNMP device.
    metrics_path: /snmp
    params:
      module: [synology]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116

  - job_name: prometheus

    honor_labels: true
    # scrape_interval is defined by the configured global (15s).
    # scrape_timeout is defined by the global default (10s).

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090", "localhost:9100"]
        # labels:
        #   my: label
        #   your: label

    relabel_configs:
      - source_labels: [job, __meta_dns_name]
        regex: (.*)some-[regex]
        target_label: job
        replacement: foo-${1}
        # action defaults to 'replace'
      - source_labels: [abc]
        target_label: cde
      - replacement: static
        target_label: abc
      - regex:
        replacement: static
        target_label: abc

    # authorization:
    #   credentials_file: valid_token_file

  - job_name: node-exporter

    file_sd_configs:
      - files:
          - targets/*.yaml
        refresh_interval: 30s

  - job_name: gitlab-nginx

    static_configs:
      - targets:
        - 10.0.0.251:8060

  - job_name: gitlab-redis

    static_configs:
      - targets:
        - 10.0.0.251:9121

  - job_name: gitlab-postgres

    static_configs:
      - targets:
        - 10.0.0.251:9187

  - job_name: gitlab-node

    static_configs:
      - targets:
        - 10.0.0.251:9100

  - job_name: gitlab-workhorse

    static_configs:
      - targets:
        - 10.0.0.251:9229

  - job_name: gitlab-rails

    metrics_path: "/-/metrics"
    static_configs:
      - targets:
        - 10.0.0.251:8080

  - job_name: gitlab-sidekiq

    static_configs:
      - targets:
        - 10.0.0.251:8082
  - job_name: gitlab_exporter_database

    metrics_path: "/database"
    static_configs:
      - targets:
        - 10.0.0.251:9168

  - job_name: gitlab_exporter_sidekiq

    metrics_path: "/sidekiq"
    static_configs:
      - targets:
        - 10.0.0.251:9168

  - job_name: gitlab_exporter_process

    metrics_path: "/process"
    static_configs:
      - targets:
        - 10.0.0.251:9168

  - job_name: gitlab-gitaly

    static_configs:
      - targets:
        - 10.0.0.251:9236
