- name: Shutdown all EC2 instances found
  hosts: localhost
  tasks:
    - name: Gather information about all instances
      debug:
        msg: "{{ item }}"
      with_items: "{{ groups['aws_ec2'] }}"

    - name: Shutdown instances
      community.aws.ec2_instance_info:
        region: "{{ aws_region }}"
      register: ec2_info

    - debug: var=ec2_info
