- name: Shutdown all EC2 instances found
  hosts: localhost
  gather_facts: no
  tasks:
    # - name: Gather information about all instances
    #   debug:
    #     msg: "{{ item }}"
    #   with_items: "{{ groups['aws_ec2'] }}"

    - name: Collect instance facts
      community.aws.ec2_instance_info:
        region: "{{ aws_region }}"
      register: ec2_info

    # - debug:
    #     msg: "{{ q('subelements',ec2_info.instances,'instance_id') }}"

    - name: Shutdown instance
      community.aws.ec2_instance:
        instance_ids: "{{ item.instance_id }}"
        state: stopped
        region: "{{ aws_region }}"
      with_items: "{{ ec2_info.instances }}"
